<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_pekerjaan</name>
   <tag></tag>
   <elementGuidId>b104167f-ca0b-4384-b725-71ae1cf82fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[13]/div[2]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;detail_pekerjaan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='detail_pekerjaan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[13]/div[2]/div/textarea</value>
      <webElementGuid>c4bc035d-cef9-4473-b3d9-62a002a8390e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='detail_pekerjaan']</value>
      <webElementGuid>a88a9434-8701-4a6f-8137-d1a4bfd961ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[13]/div[2]/div/textarea</value>
      <webElementGuid>1a855162-ea96-424c-8149-df955f8959be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pekerjaan'])[1]/following::textarea[1]</value>
      <webElementGuid>8face153-3f26-421f-9134-66be2ba0e0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Path/Filename'])[1]/following::textarea[1]</value>
      <webElementGuid>cb51801d-5e43-49b4-8975-d948d1c3b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Kerja'])[1]/preceding::textarea[1]</value>
      <webElementGuid>152ac27c-ce47-423b-b1b1-e4f9ddb1c3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[3]/preceding::textarea[1]</value>
      <webElementGuid>22e3ea25-86c6-47a6-8d12-3774a64f191b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0938a099-7ea4-433b-a4ca-0d1397a0217c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Detail Pekerjaan...' and @name = 'detail_pekerjaan']</value>
      <webElementGuid>05752e4e-02ab-4fbc-879d-30ad379669cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
