<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hasil</name>
   <tag></tag>
   <elementGuidId>4282f5f1-c349-4c70-91a8-d4d95098a898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[9]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;hasil&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='hasil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[9]/div[2]/div/input</value>
      <webElementGuid>b3dd6d5f-eff2-47f5-afd4-4d7847b35646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='hasil']</value>
      <webElementGuid>910aaef7-0466-4cd7-bab4-6983128e82b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[9]/div[2]/div/input</value>
      <webElementGuid>02757f45-60f5-41a6-a657-bb8529d1d797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil'])[1]/following::input[1]</value>
      <webElementGuid>48d0563c-29ea-4a71-940b-109f2b6153ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kegiatan'])[1]/following::input[1]</value>
      <webElementGuid>b6f56b49-88aa-460f-b733-f732328a829b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capaian'])[1]/preceding::input[1]</value>
      <webElementGuid>33742b55-2a70-4508-8f82-f37170dd887d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/preceding::input[2]</value>
      <webElementGuid>c88dd4ec-20e5-4f77-9bcf-41c751a87f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>95d17459-5d5f-4dd6-b6df-1323a1748160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hasil']</value>
      <webElementGuid>eac7d97b-8130-4d8c-b4e9-f3365e35f6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
