<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popup_success</name>
   <tag></tag>
   <elementGuidId>6103707b-86c2-496e-b536-874fce4cf289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]</value>
      <webElementGuid>dcd42612-f742-4894-9b03-86c334dc16be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
