<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>waktu_kerja</name>
   <tag></tag>
   <elementGuidId>3333151a-5b98-410b-bf3e-0636590107be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[14]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;waktu_kerja&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='waktu_kerja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div[4]/div[1]/div/div/form/div/div[2]/div[14]/div[2]/div/select</value>
      <webElementGuid>c4e01480-0527-4cc5-bbf5-a48b91c80607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='waktu_kerja']</value>
      <webElementGuid>ee7fe6da-5081-43f3-a352-76ea1d0c14d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div[4]/div/div/div/form/div/div[2]/div[14]/div[2]/div/select</value>
      <webElementGuid>b15d659d-2f97-457c-8367-3a27c128f63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Kerja'])[1]/following::select[1]</value>
      <webElementGuid>47df4b11-7f96-4140-86e0-ee72dd980e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pekerjaan'])[1]/following::select[1]</value>
      <webElementGuid>c5ec7325-d484-4521-90a5-d76370c55a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[3]/preceding::select[1]</value>
      <webElementGuid>17eb6197-172d-46c8-8e56-6884ca32a295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>2cb731d3-78a2-4016-ac84-23429ad78be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/select</value>
      <webElementGuid>e9f0852b-6721-469d-8e4c-24bf16544ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '--Select--' and @name = 'waktu_kerja' and (text() = '--Select--Jam NormalJam Lembur' or . = '--Select--Jam NormalJam Lembur')]</value>
      <webElementGuid>929214d9-9b7f-4921-8152-c81f5c61ad43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
