<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cuti_handle_empty</name>
   <tag></tag>
   <elementGuidId>2e9bb843-f22a-482a-81d5-fe035b7887f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]</value>
      <webElementGuid>4f83d8eb-3e0e-4b5a-92d3-8da27aafe958</webElementGuid>
   </webElementProperties>
</WebElementEntity>
