<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keterangan</name>
   <tag></tag>
   <elementGuidId>ce95e8f5-70da-4753-854f-ee4a7769b40d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/textarea[1]</value>
      <webElementGuid>90b2fb2e-9ef7-4d1e-ba3e-a8aca4f91213</webElementGuid>
   </webElementProperties>
</WebElementEntity>
