<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>success_message</name>
   <tag></tag>
   <elementGuidId>aa9e0717-d255-41cc-a16a-4853c21a2f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]</value>
      <webElementGuid>7c0daa12-6356-41b9-836c-f2132a04c103</webElementGuid>
   </webElementProperties>
</WebElementEntity>
