<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl</name>
   <tag></tag>
   <elementGuidId>247c7387-8c3c-4972-87d9-e6099772e9d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]</value>
      <webElementGuid>5a930d9c-2f12-4d86-a574-13a69ef80b82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
