<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl_start</name>
   <tag></tag>
   <elementGuidId>cb9a50c7-5fa8-4a22-8782-4e5c41e32cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[1]/div[1]/div/form/div/div/div[1]/div/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[1]/div[1]/div/form/div/div/div[1]/div/span[1]/input</value>
      <webElementGuid>993a38c1-5e93-4a3b-a003-452223c79c66</webElementGuid>
   </webElementProperties>
</WebElementEntity>
