<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ttd</name>
   <tag></tag>
   <elementGuidId>42982642-7c7a-4fa5-a9b7-89e142054070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[3]/div/main/div/div/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div/canvas</value>
      <webElementGuid>1ad0bb0f-e048-4b45-a6d1-ab170ed297f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
