<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>handle_lembur_empty</name>
   <tag></tag>
   <elementGuidId>68b71596-0b98-4356-81ee-0adb2aa4a5c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[3]</value>
      <webElementGuid>ab58ddb0-ed9e-458a-a783-f33a5ffad502</webElementGuid>
   </webElementProperties>
</WebElementEntity>
