<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ket</name>
   <tag></tag>
   <elementGuidId>4225392c-0ed3-4dec-a2cf-e21537f5b7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='keterangan_lembur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;keterangan_lembur&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[1]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[1]/div/textarea</value>
      <webElementGuid>12a7c231-d402-4a5d-a299-013729807b7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='keterangan_lembur']</value>
      <webElementGuid>32144fff-182a-400c-9420-2c0df9b59502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div/div/textarea</value>
      <webElementGuid>a85696c6-311e-4765-8f35-32e71fe7cd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e891f49e-1a5d-4815-96df-d3151799c537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Masukan keterangan..' and @name = 'keterangan_lembur']</value>
      <webElementGuid>ecf51eef-a699-4e43-b8fc-0b3fbe41cb32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
