<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lembur_menu</name>
   <tag></tag>
   <elementGuidId>a25c09bb-bfec-4cbe-8100-9d8ec0840e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[2]/div/div/li[2]/a</value>
      <webElementGuid>cf84f1fd-56de-4f67-804a-6c8b5e0e77b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
