<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pic</name>
   <tag></tag>
   <elementGuidId>424698ca-ee16-481b-97be-cd55853a243e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='id_pic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;id_pic&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>3f27a733-c6d4-4f6a-abee-eeff510a4fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='id_pic']</value>
      <webElementGuid>39a0d5c0-a4f3-43a6-9021-b3645e9c4d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>2c04a606-a835-48e8-baf1-8d8c163f634b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama PIC'])[1]/following::select[1]</value>
      <webElementGuid>be803e71-067f-4c39-83e6-d849bd48be55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Lembur'])[1]/following::select[2]</value>
      <webElementGuid>d86296e7-e6ad-475a-9018-a6d954367211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan Lembur'])[1]/preceding::select[1]</value>
      <webElementGuid>09469ffc-9861-4b84-b2f3-90183fafadd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanda Tangan Digital'])[1]/preceding::select[1]</value>
      <webElementGuid>186e5e44-050f-492a-ae23-eaa6cdb0e241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>47f4e7fd-0519-49e2-bbd4-b99a63137f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = '-Select-' and @name = 'id_pic' and (text() = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT Test Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111' or . = '--Select--AdminyanragaTris Retno AryaniTris R ATestingDemoAppTesting123Testing Karyawan Baru scTestDev1TestAccountPM1test uat2Test UAT Test Karyawan BaruSUHERMAN RIYANTOSanti Dwi Astuti123RonaldoRamdanProject Managet TestProject Manager PrimaMikala FazaMika AnasMentari muliaMentari muliaMentari muliaLovensia Zukruff AlbasitJohn Data AnalystIka AnasherviHaeranierina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiaerina fadilah palu gada indonesiabzBAMBANG ARIFINasdAndriAhlan RezkiAgus Setyaadnan111')]</value>
      <webElementGuid>3ff7e40a-4d27-4373-a620-2886185cb98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
