<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ttd</name>
   <tag></tag>
   <elementGuidId>4ebf3c19-1adc-4b2e-b10e-ec9847fe4633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.sigPadRef</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/div/canvas</value>
      <webElementGuid>b64fcdbc-d9ee-45da-8ce0-ca2f14e21ac3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/main/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/div/canvas</value>
      <webElementGuid>ababa7f4-9c79-458c-a461-6e3aac1a918c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>7a325a68-d733-4357-9c3b-c7c19b0dd903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
