<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copyright_welcomepage</name>
   <tag></tag>
   <elementGuidId>c25a9e66-e0e8-4c3c-a202-b30f45100f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[2]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[2]/div[2]/span</value>
      <webElementGuid>ce79f3a5-6f2b-4e3a-ae58-8a830e76730a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
