<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_icon</name>
   <tag></tag>
   <elementGuidId>534c97b0-3cd3-4984-a99b-c54d962d1ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/header/ul[3]/li/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[3]/header/ul[3]/li/a/div/img</value>
      <webElementGuid>76d09d72-004c-4817-844c-b57dd48f0997</webElementGuid>
   </webElementProperties>
</WebElementEntity>
