<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signout</name>
   <tag></tag>
   <elementGuidId>71acf33a-c032-4f2f-92de-fd378d0a017e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/header/ul[3]/li/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div/div[3]/header/ul[3]/li/div/a</value>
      <webElementGuid>b62701de-7c09-4f15-8e9a-34170c5f4ecc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
