<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>welcome_title</name>
   <tag></tag>
   <elementGuidId>761b25d5-3a62-44be-b5c2-044c6d0c860d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[2]/div[1]/div/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[2]/div[1]/div/div/div/div/h4</value>
      <webElementGuid>6b51fa45-4385-4edc-9b43-4a17e0824471</webElementGuid>
   </webElementProperties>
</WebElementEntity>
