<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_final</name>
   <tag></tag>
   <elementGuidId>c8857434-679d-4568-a38b-3721b1871456</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[contains(text(),'OK')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[contains(text(),'OK')]</value>
      <webElementGuid>caf8070d-c982-42f2-b6e6-a5a84b942342</webElementGuid>
   </webElementProperties>
</WebElementEntity>
