<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>final_success</name>
   <tag></tag>
   <elementGuidId>661857f4-5864-4084-88ac-10a1c61d18c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'Success')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'Success')]</value>
      <webElementGuid>40bf585b-a2b3-4731-bf4d-eaff341adde4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
