<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addlogbook_btn</name>
   <tag></tag>
   <elementGuidId>cdb2bbc0-b9a9-4c39-8cc6-36c78118c455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/div[@id='root']/div[1]/div[3]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]</value>
      <webElementGuid>0601c10d-d33f-495b-ae08-f579d8c63e09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
